

export const AppRoutesPaths = {
    notFound: "*",
    adminHomePage: "/admin/home",
    adminServicesPage: "/admin/services",
    adminPersonnelPage: "/admin/personnel",
    adminChambresPage: "/admin/chambres",
    welcomePage: "/",
    loginPage: "/login",
    forgottenPasswordPage: "/forgotten-password",
    pharmacyPage: "/pharmacy",
    pharmacyHistoryPage: "/pharmacy/history",
    pharmacyReportsPage: "/pharmacy/reports",
    pharmacyNeedsPage: "/pharmacy/needs",
    doctorPage: "/doctor/waiting-room",
    laboratoryAssistantPage: "/laboratory-assistant/home",
    receptionistPage: "/receptionist/patients",
    cashierPage: "/cashier/consultation-list",
    consultationsList: "/cashier/consultations-list",
    examsList: "/cashier/exams-list",
    hospitalisations: "/cashier/hospitalisations-list",
    financialReport: "/cashier/financial-report",
    helpCenter: "/cashier/help-center",
    specialistPage: "/specialist",
    nursePage: "/nurse/waiting-room",
    nurseWaitingRoomPage: "/nurse/waiting-room",
    nurseAppointmentsPage: "/nurse/appointments",
    nurseMedicalStaffsPage: "/nurse/medical-staff",
    consultationHistoryPage: "/nurse/patients/consultation-history/:id",
    helpCenterPage: "/help-center",
    patientDetailsPage: "/nurse/patients/take-parameters/:id",
    receptionistMedicalStaffsPage: "/receptionist/medical-staffs",
    appointmentsPage: "/receptionist/appointments",
    hospitalizedPatientsPage: "/receptionist/hospitalized",
    adminPatientListPage: "/admin/patient-list",
    addDrug: "/admin/add-drug",
    adminDrugsListPage: "/admin/drugs-list",
    addMedicalStaff: "/admin/add-medical-staff",
    adminMedicalStaffListPage: "/admin/medical-staff-list",
    adminConsultationListPage: "/admin/consultation-list",
    adminAppointmentsListPage: "/admin/appointments-list",
    addExam: "/admin/add-exam",
    adminExamsListPage: "/admin/exams-list",
    adminHospitalRoomPage: "/admin/room-list",
    adminFinancialReportsPage: "/admin/financial-report",
    accountantPage: "/accountant/dashboard",
    adminConsultationDetailsPage: "/admin/consultation-list/details",
    laboratoryHistory: "/laboratory/exams-history",
    laboratoryCurrent: "/laboratory/current-exams",
    financialHistory: "/cashier/financial-history",
    accountDetails: "/accountant/account-details/:accountId",
    accountList: "/accountant/account-list",
    doctorPatientList: "/doctor/patients",
    doctorConsultationList: "/doctor/consultation-list",
    doctorConsultationDetailsPage: "/doctor/consultation-list/details/:id",
    doctorAppointment: "/doctor/appointments",
    doctorConsultationHistory: "/doctor/consultation-history",
    doctorConsultationHistoryDetails: "/doctor/consultation-history/details/:id",
    doctorExamList: "/doctor/exams-list",
    doctorPatientMedicalFolderPage: "/doctor/patients/medical-folder/:id",
    financialContributions: "/accountant/financial-contributions",
    financialReportsAccountant: "/accountant/financial-reports",
    PharmacyMedication: "/pharmacyMedication",
    createFactureAccountant: "/accountant/create-facture",

    laboratoryPatientList: "/laboratory-assistant/patient-list",
    laboratoryExamenList: "/laboratory-assistant/exams-list",
    laboratoryExamenDetail: "/laboratory-assistant/exams-list/details/:id",
    laboratoryExamenHistories: "/laboratory-assistant/exams-history",
    laboratoryExamResultDetails: "/laboratory-assistant/exams-history/details/:id",
    laboratoryNotification: "/laboratory-assistant/notifications",

    financialAccountantHome: "/accountant-financial/home",
    financialAccountantChartOfAccount: "/accountant-financial/chart-account",
    financialAccountantJournalEntries: "/accountant-financial/journat-entries",
    financialAccountantAccountingJournals: "/accountant-financial/accounting-journals",
    financialAccountantAccountingGrandLivre: "/accountant-financial/accounting-grand-livre",
    financialAccountantInvoices: "/accountant-financial/invoices",
    financialAccountantPayments: "/accountant-financial/payments",
    financialAccountantBudgets: "/accountant-financial/budgets",
    financialAccountantReports: "/accountant-financial/reports",
    financialAccountPayroll: "/accountant-financial/payroll-journal",
    financialAccountantCostAnalytic: "/accountant-financial/cost-analytic",

    // ComptaMatiere (Comptable Matière) routes
    comptaMatiereDashboard: "/compta-matiere/dashboard",
    comptaMatiereEmitNeed: "/compta-matiere/emit-need",
    comptaMatiereRegisterDelivery: "/compta-matiere/register-delivery",
    comptaMatiereRegisterOutput: "/compta-matiere/register-output",
    comptaMatiereReports: "/compta-matiere/reports",
    comptaMatiereMaterialList: "/compta-matiere/material-list",
    comptaMatiereOutputList: "/compta-matiere/output-list",

    // Director routes
    directorDashboard: "/director/dashboard",
    directorReports: "/director/reports",

    // Pharmacist routes
    pharmacistDashboard: "/pharmacist/dashboard",
    pharmacistEmitNeed: "/pharmacist/emit-need",
    pharmacistDailySales: "/pharmacist/daily-sales",
    pharmacistInventory: "/pharmacist/inventory",
    pharmacistReports: "/pharmacist/reports"

}
