

export const AppRoutesPaths = {
    notFound: "*",
    adminHomePage: "/admin/home",
    adminServicesPage: "/admin/services",
    adminPersonnelPage: "/admin/personnel",
    adminChambresPage: "/admin/chambres",
    welcomePage: "/",
    loginPage: "/login",
    forgottenPasswordPage: "/forgotten-password",
    pharmacyPage: "/pharmacy",
    pharmacyHistoryPage: "/pharmacy/history",
    pharmacyReportsPage: "/pharmacy/reports",
    pharmacyNeedsPage: "/pharmacy/needs",
    doctorPage: "/doctor/waiting-room",
    laboratoryAssistantPage: "/laboratory-assistant/home",
    receptionistPage: "/receptionist/patients",
    cashierPage: "/cashier/consultation-list",
    consultationsList: "/cashier/consultations-list",
    examsList: "/cashier/exams-list",
    hospitalisations: "/cashier/hospitalisations-list",
    financialReport: "/cashier/financial-report",
    helpCenter: "/cashier/help-center",
    specialistPage: "/specialist",
    nursePage: "/nurse/waiting-room",
    nurseWaitingRoomPage: "/nurse/waiting-room",
    nurseAppointmentsPage: "/nurse/appointments",
    nurseMedicalStaffsPage: "/nurse/medical-staff",
    consultationHistoryPage: "/nurse/patients/consultation-history/:id",
    helpCenterPage: "/help-center",
    patientDetailsPage: "/nurse/patients/take-parameters/:id",
    receptionistMedicalStaffsPage: "/receptionist/medical-staffs",
    appointmentsPage: "/receptionist/appointments",
    hospitalizedPatientsPage: "/receptionist/hospitalized",
    adminPatientListPage: "/admin/patient-list",
    addDrug: "/admin/add-drug",
    adminDrugsListPage: "/admin/drugs-list",
    addMedicalStaff: "/admin/add-medical-staff",
    adminMedicalStaffListPage: "/admin/medical-staff-list",
    adminConsultationListPage: "/admin/consultation-list",
    adminAppointmentsListPage: "/admin/appointments-list",
    addExam: "/admin/add-exam",
    adminExamsListPage: "/admin/exams-list",
    adminHospitalRoomPage: "/admin/room-list",
    adminFinancialReportsPage: "/admin/financial-report",
    adminConsultationDetailsPage: "/admin/consultation-list/details",
    laboratoryHistory: "/laboratory/exams-history",
    laboratoryCurrent: "/laboratory/current-exams",
    financialHistory: "/cashier/financial-history",
    doctorPatientList: "/doctor/patients",
    doctorConsultationList: "/doctor/consultation-list",
    doctorConsultationDetailsPage: "/doctor/consultation-list/details/:id",
    doctorAppointment: "/doctor/appointments",
    doctorConsultationHistory: "/doctor/consultation-history",
    doctorConsultationHistoryDetails: "/doctor/consultation-history/details/:id",
    doctorExamList: "/doctor/exams-list",
    doctorPatientMedicalFolderPage: "/doctor/patients/medical-folder/:id",
    PharmacyMedication: "/pharmacyMedication",

    laboratoryPatientList: "/laboratory-assistant/patient-list",
    laboratoryExamenList: "/laboratory-assistant/exams-list",
    laboratoryExamenDetail: "/laboratory-assistant/exams-list/details/:id",
    laboratoryExamenHistories: "/laboratory-assistant/exams-history",
    laboratoryExamResultDetails: "/laboratory-assistant/exams-history/details/:id",
    laboratoryNotification: "/laboratory-assistant/notifications",

    // Accountant Module (New)
    accountantHome: "/accountant/home",
    accountantQuittancesAValider: "/accountant/quittances/a-valider",
    accountantQuittancesValidees: "/accountant/quittances/validees",
    accountantPlanComptable: "/accountant/plan-comptable",
    accountantVentilation: "/accountant/ventilation",
    accountantRapports: "/accountant/rapports",
}

