

export const AppRoutesPaths = {
    notFound: "*",
    adminHomePage: "/admin/home",
    adminServicesPage: "/admin/services",
    adminPersonnelPage: "/admin/personnel",
    adminChambresPage: "/admin/chambres",
    welcomePage: "/",
    loginPage: "/login",
    forgottenPasswordPage: "/forgotten-password",

    doctorPage: "/doctor/waiting-room",
    laboratoryAssistantPage: "/laboratory-assistant/home",
    receptionistPage: "/receptionist/patients",
    cashierPage: "/cashier/consultation-list",
    consultationsList: "/cashier/consultations-list",
    examsList: "/cashier/exams-list",
    hospitalisations: "/cashier/hospitalisations-list",
    financialReport: "/cashier/financial-report",
    helpCenter: "/cashier/help-center",
    specialistPage: "/specialist",
    nursePage: "/nurse/waiting-room",
    nurseWaitingRoomPage: "/nurse/waiting-room",
    nurseAppointmentsPage: "/nurse/appointments",
    nurseMedicalStaffsPage: "/nurse/medical-staff",
    consultationHistoryPage: "/nurse/patients/consultation-history/:id",
    helpCenterPage: "/help-center",
    patientDetailsPage: "/nurse/patients/take-parameters/:id",
    receptionistMedicalStaffsPage: "/receptionist/medical-staffs",
    appointmentsPage: "/receptionist/appointments",
    hospitalizedPatientsPage: "/receptionist/hospitalized",
    adminPatientListPage: "/admin/patient-list",
    addDrug: "/admin/add-drug",
    adminDrugsListPage: "/admin/drugs-list",
    addMedicalStaff: "/admin/add-medical-staff",
    adminMedicalStaffListPage: "/admin/medical-staff-list",
    adminConsultationListPage: "/admin/consultation-list",
    adminAppointmentsListPage: "/admin/appointments-list",
    addExam: "/admin/add-exam",
    adminExamsListPage: "/admin/exams-list",
    adminHospitalRoomPage: "/admin/room-list",
    adminFinancialReportsPage: "/admin/financial-report",
    adminConsultationDetailsPage: "/admin/consultation-list/details",
    laboratoryHistory: "/laboratory/exams-history",
    laboratoryCurrent: "/laboratory/current-exams",
    financialHistory: "/cashier/financial-history",
    doctorPatientList: "/doctor/patients",
    doctorConsultationList: "/doctor/consultation-list",
    doctorConsultationDetailsPage: "/doctor/consultation-list/details/:id",
    doctorAppointment: "/doctor/appointments",
    doctorConsultationHistory: "/doctor/consultation-history",
    doctorConsultationHistoryDetails: "/doctor/consultation-history/details/:id",
    doctorExamList: "/doctor/exams-list",
    doctorPatientMedicalFolderPage: "/doctor/patients/medical-folder/:id",

    laboratoryPatientList: "/laboratory-assistant/patient-list",
    laboratoryExamenList: "/laboratory-assistant/exams-list",
    laboratoryExamenDetail: "/laboratory-assistant/exams-list/details/:id",
    laboratoryExamenHistories: "/laboratory-assistant/exams-history",
    laboratoryExamResultDetails: "/laboratory-assistant/exams-history/details/:id",
    laboratoryNotification: "/laboratory-assistant/notifications",

    // ComptaMatiere (Comptable Matière) routes
    comptaMatiereDashboard: "/compta-matiere/dashboard",
    comptaMatiereEmitNeed: "/compta-matiere/emit-need",
    comptaMatiereRegisterDelivery: "/compta-matiere/register-delivery",
    comptaMatiereRegisterOutput: "/compta-matiere/register-output",
    comptaMatiereReports: "/compta-matiere/reports",
    comptaMatiereMaterialList: "/compta-matiere/material-list",
    comptaMatiereOutputList: "/compta-matiere/output-list",

    // Director routes
    directorDashboard: "/director/dashboard",
    directorReports: "/director/reports",

    // Pharmacist routes
    pharmacistDashboard: "/pharmacist/dashboard",
    pharmacistPrescriptions: "/pharmacist/prescriptions",
    pharmacistMedicationList: "/pharmacist/medication-list",
    pharmacistEmitNeed: "/pharmacist/emit-need",
    pharmacistDailySales: "/pharmacist/daily-sales",
    pharmacistInventory: "/pharmacist/inventory",
    pharmacistReports: "/pharmacist/reports",

    // Accountant Module (New - from prototype)
    accountantHome: "/accountant/home",
    accountantQuittancesAValider: "/accountant/quittances/a-valider",
    accountantQuittancesValidees: "/accountant/quittances/validees",
    accountantEcritures: "/accountant/ecritures",
    accountantBalance: "/accountant/balance",
    accountantPlanComptable: "/accountant/plan-comptable",
    accountantRapports: "/accountant/rapports"
}
